//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupuriDeStudiuIP35
{
    using System;
    using System.Collections.Generic;
    
    public partial class APARTENENTA
    {
        public int IdUtilizator { get; set; }
        public int IdGrup { get; set; }
        public string Rol { get; set; }
        public int Id { get; set; }
    
        public virtual GRUPURI GRUPURI { get; set; }
        public virtual UTILIZATORI UTILIZATORI { get; set; }
    }
}
