//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupuriDeStudiuIP35
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERII
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERII()
        {
            this.GRUPURIs = new HashSet<GRUPURI>();
        }
    
        public int Id { get; set; }
        public string Denumire { get; set; }
        public string ProfesorCurs { get; set; }
        public int An { get; set; }
        public string Specializare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPURI> GRUPURIs { get; set; }
    }
}
