//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupuriDeStudiuIP35
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBIECTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBIECTE()
        {
            this.DISCUTIIs = new HashSet<DISCUTII>();
        }
    
        public int Id { get; set; }
        public int IdGrup { get; set; }
        public int IdUtilizator { get; set; }
        public string Text { get; set; }
        public System.DateTime Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUTII> DISCUTIIs { get; set; }
        public virtual GRUPURI GRUPURI { get; set; }
        public virtual UTILIZATORI UTILIZATORI { get; set; }
    }
}
