//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupuriDeStudiuIP35
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILIZATORI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UTILIZATORI()
        {
            this.DISCUTIIs = new HashSet<DISCUTII>();
            this.MATERIALEs = new HashSet<MATERIALE>();
            this.SUBIECTEs = new HashSet<SUBIECTE>();
            this.APARTENENTAs = new HashSet<APARTENENTA>();
            this.CERERIs = new HashSet<CERERI>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Tip { get; set; }
        public Nullable<int> Grupa { get; set; }
        public string Materie { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public byte[] Poza { get; set; }
        public string Parola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUTII> DISCUTIIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALE> MATERIALEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBIECTE> SUBIECTEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APARTENENTA> APARTENENTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERERI> CERERIs { get; set; }
    }
}
